[tls]

[tls.stores]

[tls.stores.default]

[tls.stores.default.defaultCertificate]
certFile = "/etc/traefik/cert"
keyFile = "/etc/traefik/cert-key"

[[tls.certificates]]
certFile = "/etc/traefik/cert"
keyFile = "/etc/traefik/cert-key"
stores = ["default"]